main: de.leonheuer.skycave.minievents.MiniEvents
name: MiniEvents
author: Hakuyamu
version: 1.3.3
api-version: 1.18
depend:
  - SkyBeeCore

commands:
  miningcube:
    permission: skybee.minievent.miningcube
  lavaevent:
    description: lavaevent command
  erze:
    aliases: ["erz", "ores", "ore"]
  booster:
    permission: skybee.oregen.command.booster