main: de.leonheuer.skycave.minievents.MiniEvents
name: MiniEvents
authors: [ Hakuyamu ]
version: 2.0.1
api-version: 1.18
depend: [ SkyBeeCore, Multiverse-Core ]

commands:
  miningcube:
    permission: skybee.minievent.miningcube
  lavaevent:
    description: lavaevent command
  erze:
    aliases: ["erz", "ores", "ore"]
  booster:
    permission: skybee.oregen.command.booster